import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import Image from "next/image";
import photo_victor from "../public/avatar.jpeg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Victor De Oliveira Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 ">
        <section className="min-h-screen max-w-7xl mx-auto">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className=" text-xl">Developed By Victor</h1>
            <ul className=" flex items-center">
              <li>
                <BsFillMoonStarsFill className=" cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className=" text-center p-10">
            <h2 className=" text-5xl py-2 text-teal-600 font-medium">
              Victor De Oliveira
            </h2>
            <h3 className=" text-2xl py-2">Software Engineer</h3>
            <div className=" relative mx-auto w-80 h-80 rounded">
              <Image src={photo_victor} fill alt={""} />
            </div>
            <h3 className=" text-2xl p-10">
              Bachelor degree in Multimedia Engineering at the ISTEC College.
            </h3>
            <p className=" text-md py-5 leading-8 text-gray-800">
              I'm available for software development internships and entry-level
              positions, with a preference for React, PHP or Unity. In Portugal,
              Canada or the European Union. Although I'm currently prioritising
              programming opportunities, I also enjoy working with 3D software,
              such as Blender and Autodesk 3ds Max. I am passionate about
              building great products and consider myself a very dedicated and
              reliable person. I'll tackle any problem until everyone is
              satisfied with the final solution. I never let my managers,
              co-workers or clients down. I'm a bi-lingual speaker (English and
              Portuguese).
            </p>
          </div>
          <div className=" text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
        </section>
      </main>
    </>
  );
}
